const { escape } = require("lodash");

const convertVouToXml = (
  vou
) => `                    <TALLYMESSAGE xmlns:UDF="TallyUDF">
<VOUCHER REMOTEID="" VCHKEY="" VCHTYPE="${
  vou.typeInfo.voucherType
}" ACTION="Create" OBJVIEW="Invoice Voucher View">
<ADDRESS.LIST TYPE="String">
    <ADDRESS>${escape(vou.fullAdress)}</ADDRESS>
</ADDRESS.LIST>
<BASICBUYERADDRESS.LIST TYPE="String">
    <BASICBUYERADDRESS>${escape(vou.fullAdress)}</BASICBUYERADDRESS>
</BASICBUYERADDRESS.LIST>
<OLDAUDITENTRYIDS.LIST TYPE="Number">
    <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
</OLDAUDITENTRYIDS.LIST>
<DATE>20230402</DATE>
<GUID></GUID>
<STATENAME>${escape(vou.stateName)}</STATENAME>
<NARRATION>${escape(vou.remark)}</NARRATION>
<COUNTRYOFRESIDENCE>${escape(vou.countryName)}</COUNTRYOFRESIDENCE>
<PARTYNAME>${escape(vou.getName)}</PARTYNAME>
 <VOUCHERTYPENAME>${vou.typeInfo.voucherType}</VOUCHERTYPENAME>
<REFERENCE>${vou.manualNo}</REFERENCE>
<VOUCHERNUMBER>${escape(vou.vouNo)}</VOUCHERNUMBER>
<PARTYLEDGERNAME>${escape(vou.getName)}</PARTYLEDGERNAME>
<BASICBASEPARTYNAME>${escape(vou.getName)}</BASICBASEPARTYNAME>
<CSTFORMISSUETYPE/>
<CSTFORMRECVTYPE/>
<FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
<PERSISTEDVIEW></PERSISTEDVIEW>
<BASICBUYERNAME>${escape(vou.getName)}</BASICBUYERNAME>
<BASICDUEDATEOFPYMT>${escape(vou.paymentTerms)}</BASICDUEDATEOFPYMT>
<VCHGSTCLASS/>
<DIFFACTUALQTY>No</DIFFACTUALQTY>
<ISMSTFROMSYNC>No</ISMSTFROMSYNC>
<ASORIGINAL>No</ASORIGINAL>
<AUDITED>No</AUDITED>
<FORJOBCOSTING>No</FORJOBCOSTING>
<ISOPTIONAL>No</ISOPTIONAL>
<EFFECTIVEDATE>20230402</EFFECTIVEDATE>
<USEFOREXCISE>No</USEFOREXCISE>
<ISFORJOBWORKIN>No</ISFORJOBWORKIN>
<ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
<USEFORINTEREST>No</USEFORINTEREST>
<USEFORGAINLOSS>No</USEFORGAINLOSS>
<USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
<USEFORCOMPOUND>No</USEFORCOMPOUND>
<USEFORSERVICETAX>No</USEFORSERVICETAX>
<ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
<EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
<USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
<IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
<EXCISEOPENING>No</EXCISEOPENING>
<USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
<ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
<ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
<ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
<INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
<ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
<ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
<IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
<ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
<ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
<ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
<ISISDVOUCHER>No</ISISDVOUCHER>
<ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
<ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
<ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
<GSTNOTEXPORTED>No</GSTNOTEXPORTED>
<IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
<ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
<ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
<ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
<ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
<ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
<ISCANCELLED>No</ISCANCELLED>
<HASCASHFLOW>No</HASCASHFLOW>
<ISPOSTDATED>No</ISPOSTDATED>
<USETRACKINGNUMBER>No</USETRACKINGNUMBER>
<ISINVOICE>${vou.typeInfo.isInvoice}</ISINVOICE>
<MFGJOURNAL>No</MFGJOURNAL>
<HASDISCOUNTS>No</HASDISCOUNTS>
<ASPAYSLIP>No</ASPAYSLIP>
<ISCOSTCENTRE>No</ISCOSTCENTRE>
<ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
<ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
<ISBLANKCHEQUE>No</ISBLANKCHEQUE>
<ISVOID>No</ISVOID>
<ISONHOLD>No</ISONHOLD>
<ORDERLINESTATUS>No</ORDERLINESTATUS>
<VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
<VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
<ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
<VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
<ISVATDUTYPAID>Yes</ISVATDUTYPAID>
<ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
<ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
<ISDELETED>No</ISDELETED>
<CHANGEVCHMODE>No</CHANGEVCHMODE>
<ALTERID> 16</ALTERID>
<MASTERID> 16</MASTERID>
<VOUCHERKEY></VOUCHERKEY>
<EXCLUDEDTAXATIONS.LIST></EXCLUDEDTAXATIONS.LIST>
<OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST>
<ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST>
<AUDITENTRIES.LIST></AUDITENTRIES.LIST>
<DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>
<SUPPLEMENTARYDUTYHEADDETAILS.LIST></SUPPLEMENTARYDUTYHEADDETAILS.LIST>
<EWAYBILLDETAILS.LIST></EWAYBILLDETAILS.LIST>
<INVOICEDELNOTES.LIST>
${
  vou.deliveryVou
    ? `<BASICSHIPPINGDATE>20230402</BASICSHIPPINGDATE>
<BASICSHIPDELIVERYNOTE>${vou.deliveryVou.vouNo}</BASICSHIPDELIVERYNOTE>`
    : ""
}
</INVOICEDELNOTES.LIST>
<INVOICEORDERLIST.LIST>${
  vou.orderVou
    ? `<BASICORDERDATE>20230402</BASICORDERDATE>
<BASICPURCHASEORDERNO>${vou.orderVou.vouNo}</BASICPURCHASEORDERNO>
`
    : ""
}</INVOICEORDERLIST.LIST>

<INVOICEINDENTLIST.LIST></INVOICEINDENTLIST.LIST>
<ATTENDANCEENTRIES.LIST></ATTENDANCEENTRIES.LIST>
<ORIGINVOICEDETAILS.LIST></ORIGINVOICEDETAILS.LIST>
<INVOICEEXPORTLIST.LIST></INVOICEEXPORTLIST.LIST>
${vou.acLedger
  .map(
    (acLedger) =>
      `<LEDGERENTRIES.LIST>
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
      </OLDAUDITENTRYIDS.LIST>
      <LEDGERNAME>${escape(acLedger.acName)}</LEDGERNAME>
      <GSTCLASS />
      <ISDEEMEDPOSITIVE>${
        vou.docCode == "SI" || vou.docCode == "PR" || vou.docCode == "DC"
          ? acLedger.acCode[0] !== "G"
            ? "Yes"
            : "No"
          : acLedger.acCode[0] == "G"
          ? "Yes"
          : "No"
      }</ISDEEMEDPOSITIVE>
      <LEDGERFROMITEM>No</LEDGERFROMITEM>
      <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
      <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
      <ISLASTDEEMEDPOSITIVE>${
        vou.docCode == "SI" || vou.docCode == "PR" || vou.docCode == "DC"
          ? acLedger.acCode[0] !== "G"
            ? "Yes"
            : "No"
          : acLedger.acCode[0] == "G"
          ? "Yes"
          : "No"
      }</ISLASTDEEMEDPOSITIVE>
      <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
      <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
      <AMOUNT>${acLedger.credit ? "" : "-"}${
        acLedger.credit ? acLedger.credit : acLedger.debit
      }</AMOUNT>
      <SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST>
      <BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST>
      <BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST>
      <INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST>
      <OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST></AUDITENTRIES.LIST>
      <INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST>
      <DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>
      <EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST></RATEDETAILS.LIST>
      <SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST>
      <STPYMTDETAILS.LIST></STPYMTDETAILS.LIST>
      <EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST>
      <TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST>
      <TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST>
      <TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST>
      <VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST>
      <COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST>
      <INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST>
      <VATITCDETAILS.LIST></VATITCDETAILS.LIST>
      <ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST>
    </LEDGERENTRIES.LIST>`
  )
  .join("")}
${vou.vouItems
  .map(
    (item) => `<ALLINVENTORYENTRIES.LIST>
    <STOCKITEMNAME>${escape(item.prodName)}</STOCKITEMNAME>
    <ISDEEMEDPOSITIVE>${
      vou.docCode == "SI" || vou.docCode == "PR" || vou.docCode == "DC"
        ? "No"
        : "Yes"
    }
    </ISDEEMEDPOSITIVE>    <ISLASTDEEMEDPOSITIVE>${
      vou.docCode == "SI" || vou.docCode == "PR" || vou.docCode == "DC"
        ? "No"
        : "Yes"
    }</ISLASTDEEMEDPOSITIVE>
    <ISAUTONEGATE>No</ISAUTONEGATE>
    <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
    <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
    <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
    <ISPRIMARYITEM>No</ISPRIMARYITEM>
    <ISSCRAP>No</ISSCRAP>
    <RATE>${item.rate}/${escape(item.UOM)}</RATE>
    <AMOUNT>${
      vou.docCode == "SI" || vou.docCode == "PR" || vou.docCode == "DC"
        ? ""
        : "-"
    }${item.qr}</AMOUNT>
    <ACTUALQTY> ${item.qty}</ACTUALQTY>
    <BILLEDQTY> ${item.qty}</BILLEDQTY>
    <BATCHALLOCATIONS.LIST>
        <GODOWNNAME>Main Location</GODOWNNAME>
        <BATCHNAME>Primary Batch</BATCHNAME>
        <INDENTNO/>
        <ORDERNO>${vou.orderVou ? vou.orderVou.vouNo : ""}</ORDERNO>
        <TRACKINGNUMBER>${
          vou.deliveryVou ? vou.deliveryVou.vouNo : ""
        }</TRACKINGNUMBER>

        <TRACKINGNUMBER/>
        <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
        <AMOUNT>${
          vou.docCode == "SI" || vou.docCode == "PR" || vou.docCode == "DC"
            ? ""
            : "-"
        }${item.qr}</AMOUNT>
        <ACTUALQTY> ${item.qty}</ACTUALQTY>
        <BILLEDQTY> ${item.qty}</BILLEDQTY>
        <ORDERDUEDATE JD="45017" P="2-Apr-2023">2-Apr-2023</ORDERDUEDATE>
        <ADDITIONALDETAILS.LIST></ADDITIONALDETAILS.LIST>
        <VOUCHERCOMPONENTLIST.LIST></VOUCHERCOMPONENTLIST.LIST>
    </BATCHALLOCATIONS.LIST>
    <ACCOUNTINGALLOCATIONS.LIST>
        <OLDAUDITENTRYIDS.LIST TYPE="Number">
            <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
        </OLDAUDITENTRYIDS.LIST>
        <LEDGERNAME>${
          vou.docCode == "SI" || vou.docCode == "SR"
            ? item.saleAcc
            : item.purcAcc
        }</LEDGERNAME>
        <GSTCLASS/>
        <ISDEEMEDPOSITIVE>${
          vou.docCode == "SI" || vou.docCode == "PR" || vou.docCode == "DC"
            ? "No"
            : "Yes"
        }
        </ISDEEMEDPOSITIVE>
        <LEDGERFROMITEM>No</LEDGERFROMITEM>
        <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
        <ISPARTYLEDGER>No</ISPARTYLEDGER>
        <ISLASTDEEMEDPOSITIVE>${
          vou.docCode == "SI" || vou.docCode == "PR" || vou.docCode == "DC"
            ? "No"
            : "Yes"
        }</ISLASTDEEMEDPOSITIVE>
        <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
        <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
        <AMOUNT>${
          vou.docCode == "SI" || vou.docCode == "PR" || vou.docCode == "DC"
            ? ""
            : "-"
        }${item.qr}</AMOUNT>
        <SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST>
        <BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST>
        <BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST>
        <INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST>
        <OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST>
        <ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST>
        <AUDITENTRIES.LIST></AUDITENTRIES.LIST>
        <INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST>
        <DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>
        <EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST>
        <RATEDETAILS.LIST></RATEDETAILS.LIST>
        <SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST>
        <STPYMTDETAILS.LIST></STPYMTDETAILS.LIST>
        <EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST>
        <TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST>
        <TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST>
        <TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST>
        <VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST>
        <COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST>
        <REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST>
        <INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST>
        <VATITCDETAILS.LIST></VATITCDETAILS.LIST>
        <ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST>
    </ACCOUNTINGALLOCATIONS.LIST>
    <DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>
    <SUPPLEMENTARYDUTYHEADDETAILS.LIST></SUPPLEMENTARYDUTYHEADDETAILS.LIST>
    <TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST>
    <REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST>
    <EXCISEALLOCATIONS.LIST></EXCISEALLOCATIONS.LIST>
    <EXPENSEALLOCATIONS.LIST></EXPENSEALLOCATIONS.LIST>
</ALLINVENTORYENTRIES.LIST>`
  )
  .join("")}
<PAYROLLMODEOFPAYMENT.LIST></PAYROLLMODEOFPAYMENT.LIST>
<ATTDRECORDS.LIST></ATTDRECORDS.LIST>
<GSTEWAYCONSIGNORADDRESS.LIST></GSTEWAYCONSIGNORADDRESS.LIST>
<GSTEWAYCONSIGNEEADDRESS.LIST></GSTEWAYCONSIGNEEADDRESS.LIST>
<TEMPGSTRATEDETAILS.LIST></TEMPGSTRATEDETAILS.LIST>
</VOUCHER></TALLYMESSAGE>
`;
const wrapperXml = `
<ENVELOPE>
<HEADER>
    <TALLYREQUEST>Import Data</TALLYREQUEST>
</HEADER>
 <BODY>
    <IMPORTDATA>
        <REQUESTDESC>
            <REPORTNAME>Vouchers</REPORTNAME>
            <STATICVARIABLES>
                <SVCURRENTCOMPANY>Test 4</SVCURRENTCOMPANY>
            </STATICVARIABLES>
        </REQUESTDESC>
        <REQUESTDATA>            </REQUESTDATA>
    </IMPORTDATA>
 </BODY>
</ENVELOPE>
`;

const convertInvVouToXml = (vou) =>
  `                <TALLYMESSAGE xmlns:UDF="TallyUDF">
<VOUCHER REMOTEID="" VCHKEY="" VCHTYPE="Stock Journal" ACTION="Create" OBJVIEW="Consumption Voucher View">
    <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
    </OLDAUDITENTRYIDS.LIST>
    <DATE>20230402</DATE>
    <GUID></GUID>
    <NARRATION>bruh</NARRATION>
    <VOUCHERTYPENAME>Stock Journal</VOUCHERTYPENAME>
    <VOUCHERNUMBER>${vou.refNo}</VOUCHERNUMBER>
    <CSTFORMISSUETYPE/>
    <CSTFORMRECVTYPE/>
    <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
    <PERSISTEDVIEW>Consumption Voucher View</PERSISTEDVIEW>
    <VCHGSTCLASS/>
    <DESTINATIONGODOWN>Main Location</DESTINATIONGODOWN>
    <DIFFACTUALQTY>No</DIFFACTUALQTY>
    <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
    <ASORIGINAL>No</ASORIGINAL>
    <AUDITED>No</AUDITED>
    <FORJOBCOSTING>No</FORJOBCOSTING>
    <ISOPTIONAL>No</ISOPTIONAL>
    <EFFECTIVEDATE>20230402</EFFECTIVEDATE>
    <USEFOREXCISE>No</USEFOREXCISE>
    <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
    <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
    <USEFORINTEREST>No</USEFORINTEREST>
    <USEFORGAINLOSS>No</USEFORGAINLOSS>
    <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
    <USEFORCOMPOUND>No</USEFORCOMPOUND>
    <USEFORSERVICETAX>No</USEFORSERVICETAX>
    <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
    <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
    <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
    <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
    <EXCISEOPENING>No</EXCISEOPENING>
    <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
    <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
    <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
    <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
    <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
    <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
    <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
    <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
    <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
    <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
    <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
    <ISISDVOUCHER>No</ISISDVOUCHER>
    <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
    <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
    <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
    <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
    <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
    <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
    <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
    <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
    <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
    <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
    <ISCANCELLED>No</ISCANCELLED>
    <HASCASHFLOW>No</HASCASHFLOW>
    <ISPOSTDATED>No</ISPOSTDATED>
    <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
    <ISINVOICE>No</ISINVOICE>
    <MFGJOURNAL>No</MFGJOURNAL>
    <HASDISCOUNTS>No</HASDISCOUNTS>
    <ASPAYSLIP>No</ASPAYSLIP>
    <ISCOSTCENTRE>No</ISCOSTCENTRE>
    <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
    <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
    <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
    <ISVOID>No</ISVOID>
    <ISONHOLD>No</ISONHOLD>
    <ORDERLINESTATUS>Yes</ORDERLINESTATUS>
    <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
    <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
    <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
    <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
    <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
    <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
    <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
    <ISDELETED>No</ISDELETED>
    <CHANGEVCHMODE>No</CHANGEVCHMODE>
    <ALTERID> 21</ALTERID>
    <MASTERID> 21</MASTERID>
    <VOUCHERKEY>193346542764200</VOUCHERKEY>
    <EXCLUDEDTAXATIONS.LIST></EXCLUDEDTAXATIONS.LIST>
    <OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST>
    <ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST>
    <AUDITENTRIES.LIST></AUDITENTRIES.LIST>
    <DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>
    <SUPPLEMENTARYDUTYHEADDETAILS.LIST></SUPPLEMENTARYDUTYHEADDETAILS.LIST>
    <EWAYBILLDETAILS.LIST></EWAYBILLDETAILS.LIST>
    <INVOICEDELNOTES.LIST></INVOICEDELNOTES.LIST>
    <INVOICEORDERLIST.LIST></INVOICEORDERLIST.LIST>
    <INVOICEINDENTLIST.LIST></INVOICEINDENTLIST.LIST>
    <ATTENDANCEENTRIES.LIST></ATTENDANCEENTRIES.LIST>
    <ORIGINVOICEDETAILS.LIST></ORIGINVOICEDETAILS.LIST>
    <INVOICEEXPORTLIST.LIST></INVOICEEXPORTLIST.LIST>
    <INVENTORYENTRIESIN.LIST>
        <STOCKITEMNAME>${vou.prodName}</STOCKITEMNAME>
        <ISDEEMEDPOSITIVE>${vou.outwardQty ? "No" : "Yes"}</ISDEEMEDPOSITIVE>
        <ISLASTDEEMEDPOSITIVE>${
          vou.inwardQty ? "No" : "Yes"
        }</ISLASTDEEMEDPOSITIVE>
        <ISAUTONEGATE>No</ISAUTONEGATE>
        <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
        <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
        <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
        <ISPRIMARYITEM>No</ISPRIMARYITEM>
        <ISSCRAP>No</ISSCRAP>
        <RATE>0</RATE>
        <AMOUNT>0</AMOUNT>
        <ACTUALQTY>${vou.inwardQty ? vou.inwardQty : vou.outwardQty}</ACTUALQTY>
        <BILLEDQTY>${vou.inwardQty ? vou.inwardQty : vou.outwardQty}</BILLEDQTY>
        <BATCHALLOCATIONS.LIST>
            <GODOWNNAME>Main Location</GODOWNNAME>
            <BATCHNAME>Primary Batch</BATCHNAME>
            <INDENTNO/>
            <ORDERNO/>
            <TRACKINGNUMBER/>
            <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
            <AMOUNT>0</AMOUNT>
            <ACTUALQTY>${
              vou.inwardQty ? vou.inwardQty : vou.outwardQty
            }</ACTUALQTY>
            <BILLEDQTY>${
              vou.inwardQty ? vou.inwardQty : vou.outwardQty
            }</BILLEDQTY>
            <ADDITIONALDETAILS.LIST></ADDITIONALDETAILS.LIST>
            <VOUCHERCOMPONENTLIST.LIST></VOUCHERCOMPONENTLIST.LIST>
        </BATCHALLOCATIONS.LIST>
        <DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>
        <SUPPLEMENTARYDUTYHEADDETAILS.LIST></SUPPLEMENTARYDUTYHEADDETAILS.LIST>
        <TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST>
        <COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST>
        <REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST>
        <EXCISEALLOCATIONS.LIST></EXCISEALLOCATIONS.LIST>
        <EXPENSEALLOCATIONS.LIST></EXPENSEALLOCATIONS.LIST>
    </INVENTORYENTRIESIN.LIST>
    <PAYROLLMODEOFPAYMENT.LIST></PAYROLLMODEOFPAYMENT.LIST>
    <ATTDRECORDS.LIST></ATTDRECORDS.LIST>
    <GSTEWAYCONSIGNORADDRESS.LIST></GSTEWAYCONSIGNORADDRESS.LIST>
    <GSTEWAYCONSIGNEEADDRESS.LIST></GSTEWAYCONSIGNEEADDRESS.LIST>
    <TEMPGSTRATEDETAILS.LIST></TEMPGSTRATEDETAILS.LIST>
</VOUCHER>
</TALLYMESSAGE>
`;
const VouConversnFn = {
  convertVouToXml,
  convertInvVouToXml,
  wrapperXml,
};
export default VouConversnFn;
