const { escape } = require("lodash");

const convertAcGrpToXml = (
  grp = { grpName: "groupName", parentGrpName: "parentGrpName" }
) => `    <TALLYMESSAGE xmlns:UDF="TallyUDF">
<GROUP NAME="" RESERVEDNAME="">
 <GUID>ca925687-9b58-410a-b109-f57908f203c0-000000be</GUID>
 <PARENT>${escape(grp.parentGrpName)}</PARENT>
 <BASICGROUPISCALCULABLE>No</BASICGROUPISCALCULABLE>
 <ADDLALLOCTYPE/>
 <GRPDEBITPARENT/>
 <GRPCREDITPARENT/>
 <ISBILLWISEON>No</ISBILLWISEON>
 <ISCOSTCENTRESON>No</ISCOSTCENTRESON>
 <ISADDABLE>No</ISADDABLE>
 <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
 <ASORIGINAL>Yes</ASORIGINAL>
 <ISSUBLEDGER>No</ISSUBLEDGER>
 <ISREVENUE>No</ISREVENUE>
 <AFFECTSGROSSPROFIT>No</AFFECTSGROSSPROFIT>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <TRACKNEGATIVEBALANCES>Yes</TRACKNEGATIVEBALANCES>
 <ISCONDENSED>No</ISCONDENSED>
 <AFFECTSSTOCK>Yes</AFFECTSSTOCK>
 <ISGROUPFORLOANRCPT>No</ISGROUPFORLOANRCPT>
 <ISGROUPFORLOANPYMNT>No</ISGROUPFORLOANPYMNT>
 <ISRATEINCLUSIVEVAT>No</ISRATEINCLUSIVEVAT>
 <ISINVDETAILSENABLE>No</ISINVDETAILSENABLE>
 <SORTPOSITION> 500</SORTPOSITION>
 <ALTERID> 219</ALTERID>
 <SERVICETAXDETAILS.LIST>      </SERVICETAXDETAILS.LIST>
 <VATDETAILS.LIST>      </VATDETAILS.LIST>
 <SALESTAXCESSDETAILS.LIST>      </SALESTAXCESSDETAILS.LIST>
 <GSTDETAILS.LIST>      </GSTDETAILS.LIST>
 <LANGUAGENAME.LIST>
  <NAME.LIST TYPE="String">
   <NAME>${escape(grp.grpName)}</NAME>
  </NAME.LIST>
  <LANGUAGEID> 1033</LANGUAGEID>
 </LANGUAGENAME.LIST>
 <XBRLDETAIL.LIST>      </XBRLDETAIL.LIST>
 <AUDITDETAILS.LIST>      </AUDITDETAILS.LIST>
 <SCHVIDETAILS.LIST>      </SCHVIDETAILS.LIST>
 <EXCISETARIFFDETAILS.LIST>      </EXCISETARIFFDETAILS.LIST>
 <TCSCATEGORYDETAILS.LIST>      </TCSCATEGORYDETAILS.LIST>
 <TDSCATEGORYDETAILS.LIST>      </TDSCATEGORYDETAILS.LIST>
 <GSTCLASSFNIGSTRATES.LIST>      </GSTCLASSFNIGSTRATES.LIST>
 <EXTARIFFDUTYHEADDETAILS.LIST>      </EXTARIFFDUTYHEADDETAILS.LIST>
</GROUP>
</TALLYMESSAGE>
`;
const convertAccToXml = (acc) => `     <TALLYMESSAGE xmlns:UDF="TallyUDF">
<LEDGER NAME="" RESERVEDNAME="">
 <ADDRESS.LIST TYPE="String">
 <ADDRESS>${escape(acc.adress.addressLine1)}</ADDRESS>
 <ADDRESS>${escape(acc.adress.addressLine2)}</ADDRESS>
 </ADDRESS.LIST>
 <MAILINGNAME.LIST TYPE="String">
  <MAILINGNAME>${escape(acc.acName)}</MAILINGNAME>
 </MAILINGNAME.LIST>
 <OLDAUDITENTRYIDS.LIST TYPE="Number">
  <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
 </OLDAUDITENTRYIDS.LIST>
 <GUID>ca925687-9b58-410a-b109-f57908f203c0-000000c0</GUID>
 <CURRENCYNAME>₹</CURRENCYNAME>
 <PINCODE>${escape(acc.adress.pincode)}</PINCODE>
 <INCOMETAXNUMBER>${escape(acc.panNo)}</INCOMETAXNUMBER>
 <COUNTRYNAME>${escape(acc.adress.countryName)}</COUNTRYNAME>
 <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
 <PARENT>${escape(acc.acGroupName)}</PARENT>
 <TAXCLASSIFICATIONNAME/>
 <TAXTYPE>Others</TAXTYPE>
 <COUNTRYOFRESIDENCE>${escape(acc.adress.countryName)}</COUNTRYOFRESIDENCE>
 <GSTTYPE/>
 <APPROPRIATEFOR/>
 <SERVICECATEGORY>&#4; Not Applicable</SERVICECATEGORY>
 <EXCISELEDGERCLASSIFICATION/>
 <EXCISEDUTYTYPE/>
 <EXCISENATUREOFPURCHASE/>
 <LEDGERFBTCATEGORY/>
 <LEDSTATENAME>${escape(acc.adress.stateName)}</LEDSTATENAME>
 <ISBILLWISEON>No</ISBILLWISEON>
 <ISCOSTCENTRESON>No</ISCOSTCENTRESON>
 <ISINTERESTON>No</ISINTERESTON>
 <ALLOWINMOBILE>No</ALLOWINMOBILE>
 <ISCOSTTRACKINGON>No</ISCOSTTRACKINGON>
 <ISBENEFICIARYCODEON>No</ISBENEFICIARYCODEON>
 <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
 <ASORIGINAL>Yes</ASORIGINAL>
 <ISCONDENSED>No</ISCONDENSED>
 <AFFECTSSTOCK>Yes</AFFECTSSTOCK>
 <ISRATEINCLUSIVEVAT>No</ISRATEINCLUSIVEVAT>
 <FORPAYROLL>No</FORPAYROLL>
 <ISABCENABLED>No</ISABCENABLED>
 <ISCREDITDAYSCHKON>No</ISCREDITDAYSCHKON>
 <INTERESTONBILLWISE>No</INTERESTONBILLWISE>
 <OVERRIDEINTEREST>No</OVERRIDEINTEREST>
 <OVERRIDEADVINTEREST>No</OVERRIDEADVINTEREST>
 <USEFORVAT>No</USEFORVAT>
 <IGNORETDSEXEMPT>No</IGNORETDSEXEMPT>
 <ISTCSAPPLICABLE>No</ISTCSAPPLICABLE>
 <ISTDSAPPLICABLE>No</ISTDSAPPLICABLE>
 <ISFBTAPPLICABLE>No</ISFBTAPPLICABLE>
 <ISGSTAPPLICABLE>No</ISGSTAPPLICABLE>
 <ISEXCISEAPPLICABLE>No</ISEXCISEAPPLICABLE>
 <ISTDSEXPENSE>No</ISTDSEXPENSE>
 <ISEDLIAPPLICABLE>No</ISEDLIAPPLICABLE>
 <ISRELATEDPARTY>No</ISRELATEDPARTY>
 <USEFORESIELIGIBILITY>No</USEFORESIELIGIBILITY>
 <ISINTERESTINCLLASTDAY>No</ISINTERESTINCLLASTDAY>
 <APPROPRIATETAXVALUE>No</APPROPRIATETAXVALUE>
 <ISBEHAVEASDUTY>No</ISBEHAVEASDUTY>
 <INTERESTINCLDAYOFADDITION>No</INTERESTINCLDAYOFADDITION>
 <INTERESTINCLDAYOFDEDUCTION>No</INTERESTINCLDAYOFDEDUCTION>
 <ISOTHTERRITORYASSESSEE>No</ISOTHTERRITORYASSESSEE>
 <OVERRIDECREDITLIMIT>No</OVERRIDECREDITLIMIT>
 <ISAGAINSTFORMC>No</ISAGAINSTFORMC>
 <ISCHEQUEPRINTINGENABLED>Yes</ISCHEQUEPRINTINGENABLED>
 <ISPAYUPLOAD>No</ISPAYUPLOAD>
 <ISPAYBATCHONLYSAL>No</ISPAYBATCHONLYSAL>
 <ISBNFCODESUPPORTED>No</ISBNFCODESUPPORTED>
 <ALLOWEXPORTWITHERRORS>No</ALLOWEXPORTWITHERRORS>
 <CONSIDERPURCHASEFOREXPORT>No</CONSIDERPURCHASEFOREXPORT>
 <ISTRANSPORTER>No</ISTRANSPORTER>
 <USEFORNOTIONALITC>No</USEFORNOTIONALITC>
 <ISECOMMOPERATOR>No</ISECOMMOPERATOR>
 <SHOWINPAYSLIP>No</SHOWINPAYSLIP>
 <USEFORGRATUITY>No</USEFORGRATUITY>
 <ISTDSPROJECTED>No</ISTDSPROJECTED>
 <FORSERVICETAX>No</FORSERVICETAX>
 <ISINPUTCREDIT>No</ISINPUTCREDIT>
 <ISEXEMPTED>No</ISEXEMPTED>
 <ISABATEMENTAPPLICABLE>No</ISABATEMENTAPPLICABLE>
 <ISSTXPARTY>No</ISSTXPARTY>
 <ISSTXNONREALIZEDTYPE>No</ISSTXNONREALIZEDTYPE>
 <ISUSEDFORCVD>No</ISUSEDFORCVD>
 <LEDBELONGSTONONTAXABLE>No</LEDBELONGSTONONTAXABLE>
 <ISEXCISEMERCHANTEXPORTER>No</ISEXCISEMERCHANTEXPORTER>
 <ISPARTYEXEMPTED>No</ISPARTYEXEMPTED>
 <ISSEZPARTY>No</ISSEZPARTY>
 <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
 <ISECHEQUESUPPORTED>No</ISECHEQUESUPPORTED>
 <ISEDDSUPPORTED>No</ISEDDSUPPORTED>
 <HASECHEQUEDELIVERYMODE>No</HASECHEQUEDELIVERYMODE>
 <HASECHEQUEDELIVERYTO>No</HASECHEQUEDELIVERYTO>
 <HASECHEQUEPRINTLOCATION>No</HASECHEQUEPRINTLOCATION>
 <HASECHEQUEPAYABLELOCATION>No</HASECHEQUEPAYABLELOCATION>
 <HASECHEQUEBANKLOCATION>No</HASECHEQUEBANKLOCATION>
 <HASEDDDELIVERYMODE>No</HASEDDDELIVERYMODE>
 <HASEDDDELIVERYTO>No</HASEDDDELIVERYTO>
 <HASEDDPRINTLOCATION>No</HASEDDPRINTLOCATION>
 <HASEDDPAYABLELOCATION>No</HASEDDPAYABLELOCATION>
 <HASEDDBANKLOCATION>No</HASEDDBANKLOCATION>
 <ISEBANKINGENABLED>No</ISEBANKINGENABLED>
 <ISEXPORTFILEENCRYPTED>No</ISEXPORTFILEENCRYPTED>
 <ISBATCHENABLED>No</ISBATCHENABLED>
 <ISPRODUCTCODEBASED>No</ISPRODUCTCODEBASED>
 <HASEDDCITY>No</HASEDDCITY>
 <HASECHEQUECITY>No</HASECHEQUECITY>
 <ISFILENAMEFORMATSUPPORTED>No</ISFILENAMEFORMATSUPPORTED>
 <HASCLIENTCODE>No</HASCLIENTCODE>
 <PAYINSISBATCHAPPLICABLE>No</PAYINSISBATCHAPPLICABLE>
 <PAYINSISFILENUMAPP>No</PAYINSISFILENUMAPP>
 <ISSALARYTRANSGROUPEDFORBRS>No</ISSALARYTRANSGROUPEDFORBRS>
 <ISEBANKINGSUPPORTED>No</ISEBANKINGSUPPORTED>
 <ISSCBUAE>No</ISSCBUAE>
 <ISBANKSTATUSAPP>No</ISBANKSTATUSAPP>
 <ISSALARYGROUPED>No</ISSALARYGROUPED>
 <USEFORPURCHASETAX>No</USEFORPURCHASETAX>
 <AUDITED>No</AUDITED>
 <SORTPOSITION> 1000</SORTPOSITION>
 <ALTERID> 222</ALTERID>
 <OPENINGBALANCE>${escape(acc.openingBalance)}</OPENINGBALANCE>
 <SERVICETAXDETAILS.LIST>      </SERVICETAXDETAILS.LIST>
 <LBTREGNDETAILS.LIST>      </LBTREGNDETAILS.LIST>
 <VATDETAILS.LIST>      </VATDETAILS.LIST>
 <SALESTAXCESSDETAILS.LIST>      </SALESTAXCESSDETAILS.LIST>
 <GSTDETAILS.LIST>      </GSTDETAILS.LIST>
 <LANGUAGENAME.LIST>
  <NAME.LIST TYPE="String">
   <NAME>${escape(acc.acName)}</NAME>
  </NAME.LIST>
  <LANGUAGEID> 1033</LANGUAGEID>
 </LANGUAGENAME.LIST>
 <XBRLDETAIL.LIST>      </XBRLDETAIL.LIST>
 <AUDITDETAILS.LIST>      </AUDITDETAILS.LIST>
 <SCHVIDETAILS.LIST>      </SCHVIDETAILS.LIST>
 <EXCISETARIFFDETAILS.LIST>      </EXCISETARIFFDETAILS.LIST>
 <TCSCATEGORYDETAILS.LIST>      </TCSCATEGORYDETAILS.LIST>
 <TDSCATEGORYDETAILS.LIST>      </TDSCATEGORYDETAILS.LIST>
 <SLABPERIOD.LIST>      </SLABPERIOD.LIST>
 <GRATUITYPERIOD.LIST>      </GRATUITYPERIOD.LIST>
 <ADDITIONALCOMPUTATIONS.LIST>      </ADDITIONALCOMPUTATIONS.LIST>
 <EXCISEJURISDICTIONDETAILS.LIST>      </EXCISEJURISDICTIONDETAILS.LIST>
 <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
 <BANKALLOCATIONS.LIST>      </BANKALLOCATIONS.LIST>
 <PAYMENTDETAILS.LIST>      </PAYMENTDETAILS.LIST>
 <BANKEXPORTFORMATS.LIST>      </BANKEXPORTFORMATS.LIST>
 <BILLALLOCATIONS.LIST>      </BILLALLOCATIONS.LIST>
 <INTERESTCOLLECTION.LIST>      </INTERESTCOLLECTION.LIST>
 <LEDGERCLOSINGVALUES.LIST>      </LEDGERCLOSINGVALUES.LIST>
 <LEDGERAUDITCLASS.LIST>      </LEDGERAUDITCLASS.LIST>
 <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
 <TDSEXEMPTIONRULES.LIST>      </TDSEXEMPTIONRULES.LIST>
 <DEDUCTINSAMEVCHRULES.LIST>      </DEDUCTINSAMEVCHRULES.LIST>
 <LOWERDEDUCTION.LIST>      </LOWERDEDUCTION.LIST>
 <STXABATEMENTDETAILS.LIST>      </STXABATEMENTDETAILS.LIST>
 <LEDMULTIADDRESSLIST.LIST>      </LEDMULTIADDRESSLIST.LIST>
 <STXTAXDETAILS.LIST>      </STXTAXDETAILS.LIST>
 <CHEQUERANGE.LIST>      </CHEQUERANGE.LIST>
 <DEFAULTVCHCHEQUEDETAILS.LIST>      </DEFAULTVCHCHEQUEDETAILS.LIST>
 <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
 <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
 <BRSIMPORTEDINFO.LIST>      </BRSIMPORTEDINFO.LIST>
 <AUTOBRSCONFIGS.LIST>      </AUTOBRSCONFIGS.LIST>
 <BANKURENTRIES.LIST>      </BANKURENTRIES.LIST>
 <DEFAULTCHEQUEDETAILS.LIST>      </DEFAULTCHEQUEDETAILS.LIST>
 <DEFAULTOPENINGCHEQUEDETAILS.LIST>      </DEFAULTOPENINGCHEQUEDETAILS.LIST>
 <CANCELLEDPAYALLOCATIONS.LIST>      </CANCELLEDPAYALLOCATIONS.LIST>
 <ECHEQUEPRINTLOCATION.LIST>      </ECHEQUEPRINTLOCATION.LIST>
 <ECHEQUEPAYABLELOCATION.LIST>      </ECHEQUEPAYABLELOCATION.LIST>
 <EDDPRINTLOCATION.LIST>      </EDDPRINTLOCATION.LIST>
 <EDDPAYABLELOCATION.LIST>      </EDDPAYABLELOCATION.LIST>
 <AVAILABLETRANSACTIONTYPES.LIST>      </AVAILABLETRANSACTIONTYPES.LIST>
 <LEDPAYINSCONFIGS.LIST>      </LEDPAYINSCONFIGS.LIST>
 <TYPECODEDETAILS.LIST>      </TYPECODEDETAILS.LIST>
 <FIELDVALIDATIONDETAILS.LIST>      </FIELDVALIDATIONDETAILS.LIST>
 <INPUTCRALLOCS.LIST>      </INPUTCRALLOCS.LIST>
 <GSTCLASSFNIGSTRATES.LIST>      </GSTCLASSFNIGSTRATES.LIST>
 <EXTARIFFDUTYHEADDETAILS.LIST>      </EXTARIFFDUTYHEADDETAILS.LIST>
 <VOUCHERTYPEPRODUCTCODES.LIST>      </VOUCHERTYPEPRODUCTCODES.LIST>
</LEDGER>
</TALLYMESSAGE>

`;
const wrapperXml = `
<ENVELOPE>
<HEADER>
<TALLYREQUEST>Import Data</TALLYREQUEST>
</HEADER>
  <BODY>
    <IMPORTDATA>
      <REQUESTDESC>
        <REPORTNAME>All Masters</REPORTNAME>
        <STATICVARIABLES>
         <SVCURRENTCOMPANY>Test 2</SVCURRENTCOMPANY>
         </STATICVARIABLES>
      </REQUESTDESC>
      <REQUESTDATA></REQUESTDATA>
    </IMPORTDATA>
  </BODY>
</ENVELOPE>`;
const accConversnFn = {
  convertAccToXml,
  convertAcGrpToXml,
  wrapperXml,
};
export default accConversnFn;
