import React, { useState } from "react";
import AuthHandler from "../../../Utils/AuthHandler";
export default function DcValues() {
  const user = AuthHandler.getUser();
  const initialValues = {
    vouNo: "X X X X",
    branchCode: user ? user.defaultBranchCode : "0000",
    docCode: "DC",
    finYear: user ? user.defaultYearCode : "0000",
    vno: "",
    manualNo: "",
    vouDate: new Date(),
    partyCode: "",
    partyName: "",
    billingAdress: "",
    billingAdressCode: "",
    shippingAdressCode: "",
    shippingAdress: "",
    paymentTermsCode: "",
    paymentTerms: "",
    remark: "",
    partyBillNo: "",
    partyBillDate: new Date(),
    partyChallanNo: "",
    partyChallanDate: new Date(),
    refType: "",
    refNo: "",
    transpotation: "",
    truckNo: "",
    agentCode: "",
    agentName: "",
    itemTotal: "",
    fright: "",
    billDisPer: "",
    billDis: "",
    roundOff: "",
    netAmount: "",
    cashCredit: "",
    receivedCash: "",
    returnCash: "",
  };

  const initialVouItem = {
    vouNo: "X",
    vouSrNo: "",
    prodCode: "",
    prodName: "",
    description: "",
    UOM: "",
    batchNo: "",
    serialNo: "",
    expDate: new Date(),
    qty: "",
    rate: "",
    qr: "",
    dqr: "",
    disPer: "",
    discount: "",
    cgstP: "",
    cgst: "",
    sgstP: "",
    sgst: "",
    igstP: "",
    igst: "",
    cessP: "",
    cess: "",
    itemAmount: "",
  };
  const initialAc = {
    acCode: "X X X X",
    acc: "",
    preFix: "",
    acGroupCode: "",
    acGroupName: "",
    acType: "",
    acName: "",
    fatherName: "",
    propritorName: "",
    tradeName: "",
    creditDays: "",
    creditAmount: "",
    panNo: "",
    aadharNo: "",
    gstNo: "",
    seedLicenNo: "",
    bankName: "",
    ifscCode: "",
    bankAcNo: "",
    acRegMob: "",
    mktArea: "",
    mktAreaCode: "",
    parentAreaCode: "",
    prdAreaCode: "",
    acStatus: "",
  };
  const initialAdress = {
    acCode: "X X X X",
    acName: "",
    // addressNo: "",
    addressLine1: "",
    addressLine2: "",
    countryCode: "",
    stateCode: "",
    regionCode: "",
    districtCode: "",
    talukaName: "",
    villageName: "",
    pincode: "",
    email: "",
    mobileno: "",
    contactNo: "",
    stateName: "",
    countryName: "",
    districtName: "",
    talukaName: "",
  };
  const initialPayValues = {
    termId: "X X X X",
    paymentTerms: "",
  };
  const initialProdValues = {
    prodCode: "X X X X",
    barcode: "",
    itemType: "",
    prodCompany: "",
    prodName: "",
    prodDesc: "",
    UOM: "",
    MRP: "",
    HSNNo: "",
    reorderLevel: "",
    maintainStock: "",
    useBatchNo: "",
    prodStatus: "",
  };
  const initialCommonValues = {
    accounts: [initialAc],
    voucherItems: [initialVouItem],
    adress: [initialAdress],
    payTerms: [initialPayValues],
    products: [initialProdValues],
  };

  const docOptions = ["DC", "QT", "GR", "SI"];
  const initialVouValues = initialValues;
  return {
    initialValues,
    initialVouItem,
    initialAc,
    initialAdress,
    initialPayValues,
    initialProdValues,
    initialCommonValues,
    initialVouValues,
  };
}
