name: docker-build ci
on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run:
       git pull origin main
       docker image rm varenyamnikam/react-app
       docker build -t react-app --no-cache .
       docker push varenyamnikam/react-app 

